### ISSUE TITLE
securityonion-docs/sguil.rst - NSMWiki

### ISSUE THREAD

**Issue by zappeee** [Security-Onion-Solutions/securityonion-docs#15]
The NSM wiki seems to be down.
The URL seems to be new, but not working either, http://www.vorant.com/nsmwiki/Main_Page

**Comment by dougburks** [comment]
Thanks for letting us know @zappeee !

I've removed the nsmwiki links:

https://github.com/Security-Onion-Solutions/securityonion-docs/commit/6fc3bca74be8ad5c4cf7bec05c238bd94093d6ca
