### ISSUE TITLE
Images for 2.0 docs

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion-docs#26]
![image](https://user-images.githubusercontent.com/1659467/87225965-c359b600-c35e-11ea-8944-87f359b203e3.png)

**Comment by m0duspwnens** [comment]
![default_portgroups_def](https://user-images.githubusercontent.com/17089008/96641876-5a85c080-12f3-11eb-90e3-0ac3d2dc9b8b.png)

![default_assignedhostgroups_def](https://user-images.githubusercontent.com/17089008/96641900-62456500-12f3-11eb-94bc-2b6874f3f4f7.png)
