### ISSUE TITLE
Hyper link issue on Wazuh page

### ISSUE THREAD

**Issue by bryant-treacle** [Security-Onion-Solutions/securityonion-docs#27]
On the Wazuh page under the Adding Agents section, the hyperlink below "Once you’ve installed the Wazuh agent...." returns a 404.  Consider replacing  with the following link.  `https://documentation.wazuh.com/3.10/user-manual/registering/using-command-line.html`

**Comment by dougburks** [comment]
The 16.04 version of this page has been updated to point to Wazuh version 3.9:
https://docs.securityonion.net/en/16.04/wazuh.html

The 2.0 version of this page has been updated to point to Wazuh version 3.10:
https://docs.securityonion.net/en/2.0/wazuh.html
