### ISSUE TITLE
Allowing Any IP to connect

### ISSUE THREAD

**Issue by mxamusic** [Security-Onion-Solutions/securityonion-docs#31]
I have Security Onion Manager Cloud based and I want to allow Any IP to connect to the Analyst Interface so how do I allow it on ```so-firewall``` or ```so-allow``` I have tried different CDIR ranges to cover all ranges but with no use

**Comment by dougburks** [comment]
Looks like you've already created a discussion in the correct place:
https://github.com/Security-Onion-Solutions/securityonion/discussions/2091

Closing this issue.
