### ISSUE TITLE
so-analyst-install script not avail pre-standard setup process

### ISSUE THREAD

**Issue by tommyluke** [Security-Onion-Solutions/securityonion-docs#34]
When I exit the standard setup process and attempt to run so-analyst-install it fails with "command not found". My work-around was to proceed with the import config (seems like the minimal approach given the options) and when that completes, I ran so-analyst-install.
Not urgent, because this seems to work fine for my needs.
But I did want to take time to comment because I interpreted the document to mean that the standard setup process need not be ran at all in order to access the analyst script.
![so-analyst-install_error](https://user-images.githubusercontent.com/15220760/104942479-82cc9c00-5982-11eb-94f6-a9f3cffe6782.png)

**Comment by m0duspwnens** [comment]
@tommyluke 
so-analyst-install is located in the SecurityOnion directory.

![image](https://user-images.githubusercontent.com/17089008/105067206-79f4cc80-5a4d-11eb-9da9-4178851826a5.png)
